Repository SlackClone/slack_clone, pull requests merged in 2020-10, with the labels that each got.

#103 can upload image on messageform and filepage to localhost
  .gitignore
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.css
  app/channels/channels_channel.rb
  app/controllers/application_controller.rb
  app/controllers/channels_controller.rb
  app/controllers/directmsgs_controller.rb
  app/controllers/messages_controller.rb
  app/controllers/uploadedfiles_controller.rb
  app/javascript/controllers/notification_controller.js
  app/javascript/controllers/uploadfile_controller.js
  app/javascript/images/PDF_file_icon.png
  app/javascript/packs/application.js
  app/javascript/packs/select2.js
  app/javascript/stylesheets/Frontend/index.js
  app/javascript/stylesheets/Frontend/upload.scss
  app/javascript/stylesheets/select2.css
  app/jobs/send_message_job.rb
  app/models/attachfile.rb
  app/models/channel.rb
  app/models/directmsg.rb
  app/models/message.rb
  app/models/message_file.rb
  app/uploaders/document_uploader.rb
  app/views/channels/show.html.erb
  app/views/messages/_message_broadcast.html.erb
  app/views/shared/_leftbar.html.erb
  app/views/shared/_msgform.html.erb
  app/views/shared/_msgform_direct.html.erb
  app/views/shared/_sharefileform.html.erb
  app/views/shared/_shareform.html.erb
  app/views/uploadedfiles/index.html.erb
  config/initializers/shrine.rb
  config/routes.rb
  db/migrate/20200926153449_create_attachfiles.rb
  db/migrate/20200930125937_create_message_files.rb
  db/schema.rb
  package.json
  spec/factories/attachfiles.rb
  spec/factories/message.rb
  spec/factories/message_files.rb
  spec/factories/user.rb
  spec/models/attachfile_spec.rb
  spec/models/message_file_spec.rb
  spec/models/message_spec.rb
  yarn.lock
Labels: feature

#105 Add emoji feature
  app/channels/channels_channel.rb
  app/controllers/messages_controller.rb
  app/javascript/controllers/channels_controller.js
  app/javascript/controllers/emoji_controller.js
  app/javascript/controllers/index.js
  app/javascript/controllers/subscribe_controller.js
  app/javascript/packs/application.js
  app/javascript/stylesheets/Frontend/shared.scss
  app/models/message.rb
  app/views/messages/_message_broadcast.html.erb
  app/views/shared/_reaction.html.erb
  babel.config.js
  config/routes.rb
  db/migrate/20200925061314_add_emojidata_to_message.rb
  db/schema.rb
  package.json
  yarn.lock
Labels: feature

#106 Ck/feature/101
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.css
  app/controllers/application_controller.rb
  app/controllers/channels_controller.rb
  app/controllers/profiles_controller.rb
  app/controllers/workspaces_controller.rb
  app/javascript/controllers/hello_controller.js
  app/javascript/packs/application.js
  app/javascript/packs/create_ch.js
  app/javascript/packs/info.js
  app/javascript/packs/reset_profile.js
  app/javascript/packs/resizing.js
  app/javascript/packs/select2.js
  app/javascript/packs/share-btn.js
  app/models/profile.rb
  app/models/user.rb
  app/models/workspace.rb
  app/uploaders/application_uploader.rb
  app/uploaders/avatar_uploader.rb
  app/uploaders/document_uploader.rb
  app/uploaders/image_uploader.rb
  app/views/channels/show.html.erb
  app/views/pages/index.html.erb
  app/views/profiles/_edit.html.erb
  app/views/profiles/edit.json.jbuilder
  app/views/profiles/show.html.erb
  app/views/shared/_header.html.erb
  app/views/shared/_invite_ch.html.erb
  app/views/shared/_invite_ws.html.erb
  app/views/shared/_right_info.html.erb
  app/views/workspaces/index.html.erb
  app/views/workspaces/new.html.erb
  config/environments/development.rb
  config/initializers/shrine.rb
  config/routes.rb
  config/webpack/environment.js
  db/migrate/20200923043256_add_image_data_to_workspaces.rb
  db/migrate/20200924033547_create_profiles.rb
  db/schema.rb
  package.json
  public/uploads/087a27deb9d6549092911e200825419f.png
  public/uploads/cache/03d900b13c94c782bc840131ff54fdbd.png
  public/uploads/cache/080a174f08cc82fffc85a9ef2e4e38b5.gif
  public/uploads/cache/3547af6712d7e165ef126b14907627a9.gif
  public/uploads/cache/52b237ffb7385abf8c4496863031fff8.gif
  public/uploads/cache/75b79bc167628f0a1a885898dfcd36e1.jpg
  public/uploads/cache/78516fd476df711b8a4f9e33538242c9.png
  public/uploads/cache/89569053f41625953a8d1580ab8883c6.jpg
  public/uploads/cache/bdf43db4ab42d974a3fc4998209a35fe.gif
  public/uploads/cache/eed90cc5815d785624fecb540bb80982.gif
  spec/factories/profiles.rb
  spec/models/profile_spec.rb
  yarn.lock
Labels: feature

#111 bug fix
  app/assets/stylesheets/application.css
  app/controllers/profiles_controller.rb
  app/javascript/packs/info.js
  app/javascript/packs/resizing.js
  app/javascript/packs/select2.js
  postcss.config.js
  public/uploads/087a27deb9d6549092911e200825419f.png
  public/uploads/cache/03d900b13c94c782bc840131ff54fdbd.png
  public/uploads/cache/080a174f08cc82fffc85a9ef2e4e38b5.gif
  public/uploads/cache/3547af6712d7e165ef126b14907627a9.gif
  public/uploads/cache/52b237ffb7385abf8c4496863031fff8.gif
  public/uploads/cache/75b79bc167628f0a1a885898dfcd36e1.jpg
  public/uploads/cache/78516fd476df711b8a4f9e33538242c9.png
  public/uploads/cache/89569053f41625953a8d1580ab8883c6.jpg
  public/uploads/cache/bdf43db4ab42d974a3fc4998209a35fe.gif
  public/uploads/cache/eed90cc5815d785624fecb540bb80982.gif
Labels: bug

#115 share and emoji btn chnage to fontawesome
  app/javascript/stylesheets/Frontend/shared.scss
  app/views/messages/_message_broadcast.html.erb
Labels: feature

#120 corrected ckeditor will double
  app/javascript/controllers/subscribe_controller.js
  app/views/uploadedfiles/index.html.erb
Labels: bug

#118 index RWD
  app/javascript/images/Sladock_logo.png
  app/javascript/images/indexImg.jpg
  app/javascript/stylesheets/Frontend/shared.scss
  app/views/layouts/application.html.erb
  app/views/pages/index.html.erb
  postcss.config.js
  public/favicon123.ico
  tailwind.config.js
Labels: feature

#128 限制暱稱長度
  app/models/user.rb
Labels: bug

#121 Ck/feature/116
  app/controllers/directmsgs_controller.rb
  app/controllers/drafts_controller.rb
  app/controllers/profiles_controller.rb
  app/javascript/controllers/subscribe_controller.js
  app/javascript/images/invite-ch.svg
  app/javascript/images/invite.svg
  app/javascript/packs/application.js
  app/javascript/packs/drafts.js
  app/javascript/stylesheets/Frontend/draft.css
  app/javascript/stylesheets/Frontend/index.js
  app/models/user.rb
  app/views/channels/show.html.erb
  app/views/drafts/show.html.erb
  app/views/profiles/_edit.html.erb
  app/views/shared/_header.html.erb
  app/views/shared/_invite_ch.html.erb
  app/views/shared/_invite_ws.html.erb
  app/views/shared/_leftbar.html.erb
  app/views/shared/_msgform.html.erb
  app/views/shared/_msgform_direct.html.erb
  app/views/uploadedfiles/index.html.erb
  app/views/workspaces/new.html.erb
  config/locales/views/en.yml
  config/locales/views/zh-TW.yml
  config/routes.rb
  tailwind.config.js
Labels: feature

#124 invitation RWD
  app/controllers/application_controller.rb
  app/javascript/images/Slack_logo_new.png
  app/javascript/stylesheets/Frontend/shared.scss
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/pages/index.html.erb
  app/views/pages/login.html.erb
  app/views/shared/_nav.html.erb
  app/views/workspaces/index.html.erb
  tailwind.config.js
Labels: feature

#130 Hank/bug/126
  app/channels/channels_channel.rb
  app/controllers/channels_controller.rb
  app/controllers/messages_controller.rb
  app/javascript/controllers/notification_controller.js
  app/javascript/controllers/subscribe_controller.js
  app/javascript/stylesheets/Frontend/index.js
  app/jobs/send_message_job.rb
  app/models/message.rb
  app/views/channels/show.html.erb
  app/views/shared/_leftbar.html.erb
  app/views/uploadedfiles/index.html.erb
Labels: bug

#134 channel show item style
  app/javascript/controllers/emoji_controller.js
  app/javascript/images/111.PNG
  app/javascript/images/get-started-workspace-tip-9764b79.png
  app/javascript/images/get_started.png
  app/views/channels/show.html.erb
  app/views/pages/login.html.erb
  app/views/shared/_header.html.erb
  app/views/shared/_language.html.erb
  app/views/shared/_leftbar.html.erb
  app/views/workspaces/new.html.erb
  app/views/workspaces/show.html.erb
  tailwind.config.js
Labels: feature

#136 Ck/feature/129
  app/controllers/channels_controller.rb
  app/controllers/directmsgs_controller.rb
  app/controllers/messages_controller.rb
  app/controllers/profiles_controller.rb
  app/javascript/packs/drafts.js
  app/javascript/packs/reset_profile.js
  app/javascript/packs/share-btn.js
  app/jobs/send_message_job.rb
  app/uploaders/avatar_uploader.rb
  app/views/channels/show.html.erb
  app/views/drafts/show.html.erb
  app/views/messages/_message_broadcast.html.erb
  config/locales/views/zh-TW.yml
  postcss.config.js
  tailwind.config.js
Labels: feature

#139 Hank/feature/135
  app/controllers/uploadedfiles_controller.rb
  app/javascript/controllers/notification_controller.js
  app/javascript/controllers/subscribe_controller.js
  app/views/drafts/show.html.erb
  app/views/shared/_leftbar.html.erb
  app/views/uploadedfiles/index.html.erb
  postcss.config.js
Labels: bug, feature

#138 Serena/feature/137
  app/javascript/images/get_started.png
  app/javascript/stylesheets/Frontend/shared.scss
  app/views/layouts/application.html.erb
  app/views/messages/_message_broadcast.html.erb
  app/views/shared/_leftbar.html.erb
  app/views/shared/_reaction.html.erb
  app/views/workspaces/new.html.erb
Labels: feature

#141 Ck/feature/140
  app/javascript/packs/resizing.js
  app/javascript/stylesheets/select2.css
  app/views/channels/show.html.erb
  app/views/drafts/show.html.erb
  app/views/pages/validate.html.erb
  app/views/profiles/_edit.html.erb
  app/views/shared/_leftbar.html.erb
  app/views/shared/_sharefileform.html.erb
  app/views/shared/_shareform.html.erb
  app/views/uploadedfiles/index.html.erb
  config/locales/utilities/en.yml
  config/locales/utilities/zh-TW.yml
  config/locales/views/en.yml
  config/locales/views/zh-TW.yml
Labels: feature

#146 解決i18n錯誤訊息
  config/locales/views/en.yml
  config/locales/views/zh-TW.yml
Labels: bug

#148 Hank/feature/144
  app/controllers/messages_controller.rb
  app/javascript/controllers/subscribe_controller.js
  app/javascript/stylesheets/Frontend/ckeditor.css
  app/javascript/stylesheets/Frontend/index.js
  app/javascript/stylesheets/Frontend/shared.scss
  app/javascript/stylesheets/Frontend/upload.scss
  app/views/messages/_message_broadcast.html.erb
  app/views/shared/_reaction.html.erb
  app/views/uploadedfiles/index.html.erb
  config/locales/views/en.yml
  config/locales/views/zh-TW.yml
  postcss.config.js
  tailwind.config.js
Labels: bug, feature

#142 Feature：Thread
  Gemfile
  Gemfile.lock
  Procfile.dev
  app/channels/channels_channel.rb
  app/controllers/directmsgs_controller.rb
  app/controllers/threads_controller.rb
  app/helpers/directmsgs_helper.rb
  app/javascript/controllers/subscribe_controller.js
  app/javascript/packs/application.js
  app/javascript/packs/info.js
  app/javascript/stylesheets/Frontend/index.js
  app/javascript/stylesheets/Frontend/shared.scss
  app/javascript/stylesheets/Frontend/thread.css
  app/javascript/stylesheets/index.js
  app/jobs/send_thread_message_job.rb
  app/models/directmsg.rb
  app/models/message.rb
  app/views/channels/_new.html.erb
  app/views/channels/show.html.erb
  app/views/drafts/show.html.erb
  app/views/messages/_message_broadcast.html.erb
  app/views/shared/_leftbar.html.erb
  app/views/shared/_right_info.html.erb
  app/views/threads/_message_broadcast.html.erb
  app/views/threads/_thread_messages.html.erb
  app/views/threads/_threadform.html.erb
  app/views/threads/_threadform_directmsg.html.erb
  app/views/uploadedfiles/index.html.erb
  config/locales/views/en.yml
  config/locales/views/zh-TW.yml
  config/routes.rb
  db/migrate/20200916063346_add_ancestry_to_message.rb
  db/schema.rb
  spec/jobs/send_notification_job_spec.rb
Labels: feature

#151 fixed share btn message
  app/javascript/packs/share-btn.js
  db/schema.rb
Labels: feature

#160 Bug Fix：fix invitation bug when thread
  app/controllers/threads_controller.rb
  app/views/channels/show.html.erb
Labels: bug

#158 email註冊及邀請格式修改
  app/controllers/invitations_controller.rb
  app/javascript/packs/drafts.js
  app/mailers/my_mailer.rb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/my_mailer/invite.html.erb
  config/initializers/devise.rb
  config/initializers/locales.rb
  config/locales/devise/devise.en.yml
  config/locales/devise/devise.zh-TW.yml
  config/locales/mailer/en.yml
  config/locales/mailer/zh-TW.yml
Labels: feature

#166 Serena/feature/157
  app/javascript/stylesheets/Frontend/shared.scss
  app/views/channels/show.html.erb
  app/views/pages/index.html.erb
  app/views/shared/_right_info.html.erb
Labels: feature

#167 Hank/feature/147
  app/controllers/channels_controller.rb
  app/controllers/directmsgs_controller.rb
  app/controllers/messages_controller.rb
  app/controllers/threads_controller.rb
  app/controllers/uploadedfiles_controller.rb
  app/controllers/webhook/github_controller.rb
  app/controllers/workspaces_controller.rb
  app/javascript/channels/consumer.js
  app/javascript/controllers/notification_controller.js
  app/javascript/controllers/subscribe_controller.js
  app/javascript/controllers/uploadfile_controller.js
  app/javascript/images/iconfinder_File.png
  app/javascript/stylesheets/Frontend/ckeditor.css
  app/javascript/stylesheets/Frontend/shared.scss
  app/jobs/send_notification_job.rb
  app/models/channel.rb
  app/models/directmsg.rb
  app/models/mention.rb
  app/models/user.rb
  app/views/channels/show.html.erb
  app/views/messages/_message_broadcast.html.erb
  app/views/shared/_leftbar.html.erb
  app/views/shared/_msgform.html.erb
  app/views/shared/_msgform_direct.html.erb
  app/views/shared/_reaction.html.erb
  app/views/shared/_right_info.html.erb
  app/views/shared/_sharefileform.html.erb
  app/views/threads/_message_broadcast.html.erb
  app/views/threads/_threadform.html.erb
  app/views/threads/_threadform_directmsg.html.erb
  app/views/uploadedfiles/index.html.erb
  app/views/workspaces/get_users.json.jbuilder
  config/locales/views/en.yml
  config/routes.rb
  db/migrate/20201011151956_create_mentions.rb
  db/schema.rb
  dump.rdb
  postcss.config.js
  spec/factories/mentions.rb
  spec/models/mention_spec.rb
Labels: bug, feature

#171 Use Mailgun 寄信
  app/controllers/invitations_controller.rb
  app/javascript/controllers/subscribe_controller.js
  app/javascript/packs/drafts.js
  app/jobs/send_email_job.rb
  app/mailers/application_mailer.rb
  app/views/layouts/application.html.erb
  app/views/my_mailer/invite.html.erb
  app/views/pages/index.html.erb
  app/views/shared/_leftbar.html.erb
  app/views/workspaces/index.html.erb
  config/environments/development.rb
  config/environments/staging.rb
  config/initializers/devise.rb
Labels: feature

#177 Hank/bug/176
  app/controllers/messages_controller.rb
  app/controllers/threads_controller.rb
  app/javascript/controllers/subscribe_controller.js
  app/models/channel.rb
  app/models/directmsg.rb
  app/models/mention.rb
  app/models/message.rb
  app/models/user.rb
  db/migrate/20201013071748_drop_mention_table.rb
  db/migrate/20201013071846_add_mention_table.rb
  db/schema.rb
  spec/models/channel_spec.rb
  spec/models/directmsg_spec.rb
  spec/models/mention_spec.rb
  spec/models/user_spec.rb
Labels: bug

#181 Hank/bug/180
  app/controllers/threads_controller.rb
  app/javascript/controllers/notification_controller.js
  app/javascript/controllers/subscribe_controller.js
  app/javascript/packs/share-btn.js
  app/jobs/send_thread_message_job.rb
  app/views/messages/_message_broadcast.html.erb
  app/views/shared/_right_info.html.erb
Labels: bug

#178 修改表單、workspace/new、drafts頁面UX
  app/controllers/channels_controller.rb
  app/controllers/profiles_controller.rb
  app/controllers/workspaces_controller.rb
  app/javascript/controllers/hello_controller.js
  app/javascript/packs/create_ch.js
  app/javascript/packs/drafts.js
  app/javascript/packs/info.js
  app/javascript/packs/invite_ws.js
  app/javascript/packs/select2.js
  app/views/channels/_new.html.erb
  app/views/channels/show.html.erb
  app/views/drafts/show.html.erb
  app/views/messages/_message_broadcast.html.erb
  app/views/profiles/_edit.html.erb
  app/views/shared/_invite_ch.html.erb
  app/views/shared/_invite_ws.html.erb
  app/views/workspaces/new.html.erb
  config/locales/views/en.yml
  config/locales/views/zh-TW.yml
Labels: feature

#185 Hank/bug/183
  app/controllers/messages_controller.rb
  app/controllers/threads_controller.rb
  app/controllers/uploadedfiles_controller.rb
  app/models/attachfile.rb
  app/models/workspace.rb
  db/migrate/20201014062550_add_attachfile_association.rb
  db/schema.rb
  lib/tasks/for_homeless_file.rake
  spec/models/attachfile_spec.rb
  spec/models/workspace_spec.rb
Labels: bug

#199 新增重寄驗證信頁面
  app/views/devise/confirmations/new.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  config/locales/devise/devise.en.yml
  config/locales/devise/devise.zh-TW.yml
  tailwind.config.js
Labels: feature

#196 Serena/feature/195
  app/javascript/packs/application.js
  app/javascript/packs/left_bar.js
  app/javascript/stylesheets/Frontend/shared.scss
  app/views/channels/show.html.erb
  app/views/layouts/application.html.erb
  app/views/pages/index.html.erb
  app/views/shared/_leftbar.html.erb
  app/views/workspaces/new.html.erb
Labels: feature

#188 Ck/feature/184
  Gemfile
  Gemfile.lock
  app/controllers/invitations_controller.rb
  app/mailers/my_mailer.rb
  app/mailers/user_mailer.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/devise.rb
  config/initializers/mail.rb
  config/locales/devise/devise.en.yml
  config/locales/devise/devise.zh-TW.yml
  tailwind.config.js
Labels: feature

#202 Serena/feature/198
  app/javascript/images/sladockIndex.png
  app/javascript/stylesheets/Frontend/shared.scss
  app/views/pages/index.html.erb
Labels: feature

#201 workspace/new RWD更新
  app/javascript/controllers/hello_controller.js
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/my_mailer/invite.html.erb
  app/views/workspaces/new.html.erb
Labels: feature

#208 Serena/feature/198
  app/javascript/stylesheets/Frontend/shared.scss
  app/views/devise/confirmations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/pages/index.html.erb
  app/views/shared/_right_info.html.erb
Labels: feature

#207 Ck/feature/206
  app/javascript/packs/application.js
  app/javascript/packs/esc.js
  app/javascript/packs/header-btn.js
  app/views/profiles/_edit.html.erb
Labels: feature

#210 index style adjustment
  app/javascript/stylesheets/Frontend/shared.scss
  app/views/pages/index.html.erb
Labels: feature

#214 Hank/bug/213
  Gemfile
  Gemfile.lock
  app/assets/images/favicon.ico
  app/channels/notification_channel.rb
  app/controllers/channels_controller.rb
  app/controllers/threads_controller.rb
  app/javascript/controllers/notification_controller.js
  app/javascript/controllers/subscribe_controller.js
  app/views/layouts/application.html.erb
  app/views/shared/_leftbar.html.erb
  app/views/uploadedfiles/index.html.erb
  config/environments/development.rb
  lib/tasks/for_homeless_file.rake
  public/favicon.ico
Labels: bug

#216 index button adjustment
  app/javascript/stylesheets/Frontend/shared.scss
  app/views/pages/index.html.erb
  app/views/pages/login.html.erb
Labels: feature

#218 更正寄信問題、修改draft/show中間div、修正上傳頁面手機版會爆版
  app/javascript/packs/esc.js
  app/mailers/my_mailer.rb
  app/mailers/user_mailer.rb
  app/views/drafts/show.html.erb
  app/views/layouts/application.html.erb
  app/views/uploadedfiles/index.html.erb
  config/environments/development.rb
  config/initializers/mail.rb
Labels: bug, feature

#222 修改index、sign in / out頁面
  app/javascript/images/sladockIndex-2.jpg
  app/javascript/stylesheets/Frontend/shared.scss
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/pages/index.html.erb
  app/views/pages/login.html.erb
  app/views/shared/_nav.html.erb
  app/views/workspaces/index.html.erb
  config/locales/devise/devise.en.yml
  tailwind.config.js
Labels: feature

#224 add rake for create demo reviewer accounts
  lib/tasks/demo.rake
  lib/tasks/demo_reviewer.rake
Labels: feature

#226 修正邀請ws第三方登入會錯誤
  app/controllers/channels_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/javascript/images/Sladock_logo.png
  app/views/layouts/application.html.erb
Labels: bug

#228 新增 sladock_logo.png
  app/javascript/images/Sladock_logo.png
  app/javascript/images/indexImg.png
  app/javascript/images/sladockIndex.png
  app/views/pages/index.html.erb
Labels: bug

#230 change rake file code
  lib/tasks/demo.rake
Labels: feature

#232 刪除input預設樣式、indexBTN跑版
  app/javascript/stylesheets/Frontend/draft.css
  app/javascript/stylesheets/Frontend/shared.scss
  app/views/pages/index.html.erb
  app/views/profiles/_edit.html.erb
  tailwind.config.js
Labels: bug
